stages:
  - test
  - build

step-develop:
  stage: test
  before_script:
    - echo here we should have the before script
  only:
    - development
  tags:
    - develpment
  script:
    - echo here we should at least running the tests

step-build:
  stage: build
  before_script:
    - echo here we should have the before script for deployment
  only:
    - master
  tags:
    - master
  script:
    - export DOCKER_GIT_CREDENTIALS="$(cat ~/.git-credentials)"
    - export REACT_APP_API_URL="http://localhost:8087"
    - docker build --build-arg DOCKER_GIT_CREDENTIALS --build-arg REACT_APP_API_URL -t registry.gitlab.com/jebo87/react-ads:0.1 .
    - docker push registry.gitlab.com/jebo87/react-ads:0.1
