stages:
  - test
  - build

step-develop:
  stage: test
  before_script:
    - echo here we should have the before script
  only:
    - development
  tags:
    - develpment
  script:
    - echo here we should at least running the tests

step-build:
  stage: build
  before_script:
    - echo here we should have the before script for deployment
  only:
    - master
  tags:
    - master
  script:
    - 'VERSION=$(curl -Ss --request GET --header "PRIVATE-TOKEN: $ACCESS_TOKEN" "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/repository/tags" | jq -r ".[0] | .name")'
    - test -z "$VERSION" && echo "no version tag found" && exit 1
    - echo 'Version '$VERSION ' was found'
    - export DOCKER_GIT_CREDENTIALS="$(cat ~/.git-credentials)"
    - docker build --build-arg DOCKER_GIT_CREDENTIALS -t registry.gitlab.com/jebo87/react-ads:$VERSION .
    - docker tag registry.gitlab.com/jebo87/react-ads:$VERSION registry.gitlab.com/jebo87/react-ads:latest
    - docker push registry.gitlab.com/jebo87/react-ads:latest
    - docker image prune -f
    - kubectl apply -f /mnt/linux/k8s/MakakoLabs/webapp-workloads.yaml
