apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: react-ads
build:
  tagPolicy:
    envTemplate:
      template: "registry.gitlab.com/jebo87/react-ads:test"
  artifacts:
    - image: registry.gitlab.com/jebo87/react-ads
      custom:
        buildCommand: ./k8s/build-skaffold.sh
deploy:
  kubectl:
    manifests:
      - k8s/webapp-workloads.yaml
